apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-identity-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5003
      protocol: TCP
  selector:
    app: tech-challenge-identity-api
